version: '3.8'
services:
  web:
    build: .
    image: migpalg.dev/expert/client:latest
    ports:
      - 8080:80

  backend:
    image: migpalg.dev/expert/api:v0.1.0-alpine
    ports:
      - 8081:8081
